### ISSUE TITLE
Tacker conf assigns localhost as heat_uri

### ISSUE THREAD

**Issue by VeenaSL** [priya-pp/fuel-plugin-tacker#1]
Configuration of tacker is wrong. By default it takes localhost as heat_uri under the section servicevm_heat in tacker.conf file because of which heat is not accessible through tacker.

Also, for authentication, instead of public_url, internal_url is considered.

**Comment by priya-pp** [comment]
corrected the values of heat_uri and keystone auth_uri. Resolved now.
